### ISSUE TITLE
seems no longer available

### ISSUE THREAD

**Issue by xclid** [55Honey/Acore_Summonall#1]
lua_scripts/Summonall.lua:32: attempt to call global 'has_value' (a nil value)

https://github.com/azerothcore/azerothcore-wotlk/commit/5330cd983c1984d77b7e050f92302d5696860fd3

**Comment by 55Honey** [comment]
Fixed in 17ec159a9fc41025a9247b09f9738b6c0abe5dd7
Please try again with the latest commit.

**Comment by xclid** [comment]
Thanks for the fix.
It works.
